# Generated by Django 6.0.4 on 2026-04-08 00:14

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=450)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('FI', 'Finalizada'), ('CA', 'Cancelada')], default='EA', max_length=2)),
            ],
        ),
    ]
