# Generated by Django 6.0.4 on 2026-04-14 02:45

import django_cpf_cnpj.fields
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('trade_name', models.CharField(max_length=100)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
            ],
        ),
    ]
